version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: graveyard_postgres
    restart: always
    environment:
      POSTGRES_USER: graveyard
      POSTGRES_PASSWORD: graveyard
      POSTGRES_DB: graveyard_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pkg/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
